---
- hosts: localhost
  gather_facts: false
  tasks:
  - name: Docker install
    ansible.builtin.yum:
     name: docker
     state: latest
  - name: Docker start
    command: 'systemctl start docker'			
